# Generated by Django 3.1.7 on 2021-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id_espaco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('lotacao', models.IntegerField()),
            ],
            options={
                'db_table': 'espaco',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('lotacao', models.IntegerField()),
            ],
            options={
                'db_table': 'sala',
            },
        ),
    ]
